hydra:
  run:
    dir: .
  output_subdir: #None
seed: 0
n_trials: 1 
T: 10000
feedback: full
noise_std: 0.1
output_dir: log
max_workers: -1
defaults:
  - _self_
  - algorithm:
    - APMD
  - game:
    - three_biased_rps
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
